import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ToasterProvider } from '@/components/providers/toaster-provider'
import { ConfettiProvider } from '@/components/providers/confetti-provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Learning M.S.',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body style={styles.bg1} className={inter.className}>
        <ConfettiProvider />
        <ToasterProvider />
        {children}
        </body>
    </html>
    </ClerkProvider>
  )
}

var styles = {
  bg1: {
    backgroundImage: "linear-gradient(180deg, #b9d4ef, #f4f7fc 25.79%)",
  }
}
